language: php

# faster builds on new travis setup not using sudo
sudo: false

php:
  - 7.1
  - 7.2
before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root

install:
  - travis_retry composer install --no-interaction

script:
  - php vendor/bin/codecept run --coverage --coverage-xml
after_success:
  - bash <(curl -s https://codecov.io/bash)