language: php

# faster builds on new travis setup not using sudo
sudo: false

php:
  - 7.3
  - 7.4

install:
  - travis_retry composer install --no-interaction

script:
  - php vendor/bin/codecept run --coverage --coverage-xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
