resources:
- name: myabstract
  type: git
  source:
    uri: https://github.com/TonisOrmisson/yii2-myabstract.git
    branch: master

jobs:
- name: run-tests
  public: true
  plan:
  - get: myabstract
    trigger: true
  - task: run tests
    privileged: true
    config:
      inputs:
      - name: myabstract
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: tonisormisson/dev-lemp

      run:
        path: sh
        args:
        - -exc
        - |
          cd myabstract

          mkdir ~/.ssh
          ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
          chmod -R 600 ~/.ssh
          ls -lst ~/.ssh
          composer install

