resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: myabstract
  type: git
  source:
    uri: https://github.com/TonisOrmisson/yii2-myabstract.git
    branch: master
- name: notify
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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


jobs:
- name: run-tests
  public: true
  plan:
  - get: myabstract
    trigger: true
  - task: run tests
    on_failure:
      put: notify
      params:
        text: "Tests failed for my-abstract"
    on_success:
      put: notify
      params:
        text: "Tests passed for my-abstract"
    privileged: true
    config:
      inputs:
      - name: myabstract
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: tonisormisson/dev-lemp

      run:
        path: sh
        args:
        - -exc
        - |
          cd myabstract

          mkdir ~/.ssh
          ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
          chmod -R 600 ~/.ssh
          ls -lst ~/.ssh
          composer install --no-interaction

